# Generated by Django 4.2.3 on 2024-01-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Employee_Mo', models.IntegerField()),
                ('Department', models.CharField(max_length=50)),
            ],
        ),
    ]
