# Generated by Django 4.2.3 on 2024-01-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Employee_Name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='employee',
            name='Salary',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
    ]
