# Generated by Django 4.2.3 on 2024-01-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0002_rename_employee_name_employee_name_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Salary',
        ),
    ]
