# Generated by Django 4.2.3 on 2024-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0003_remove_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('SampID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='Employee_Name',
        ),
    ]
