# Generated by Django 4.2.3 on 2024-01-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0004_samplemodel_rename_name_employee_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Employee_Name',
            new_name='Name',
        ),
    ]
